# -*- mode: ruby -*-
# vi: set ft=ruby :
#instalar hostmanager plugin
#
Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.provision "shell", inline: <<-SHELL
        echo "192.168.56.11 ubuntu1" >> /etc/hosts
        echo "192.168.56.12 ubuntu2" >> /etc/hosts
    SHELL
    config.vm.define :ubuntu1 do |ubuntu_config|
        ubuntu_config.vm.hostname = "ubuntu1.vm"
        ubuntu_config.vm.network "private_network" , ip:"192.168.56.11"
        ubuntu_config.vm.synced_folder ".","/vagrant"
        ubuntu_config.vm.provider :virtualbox do |vb|
            vb.name = "ubuntu1"
            vb.customize ["modifyvm", :id, "--memory", "2048"]
            vb.customize ["modifyvm", :id, "--cpus", "2"]
        end
    end
    config.vm.define :ubuntu2 do |ubuntu_config|
        ubuntu_config.vm.hostname = "ubuntu2.vm"
        ubuntu_config.vm.network "private_network" , ip:"192.168.56.12"
        ubuntu_config.vm.synced_folder ".","/vagrant"
        ubuntu_config.vm.provider :virtualbox do |vb|
            vb.name = "ubuntu2"
            vb.customize ["modifyvm", :id, "--memory", "2048"]
            vb.customize ["modifyvm", :id, "--cpus", "2"]
        end
    end
end
