# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    # config.vm.provision "shell", inline: <<-SHELL
    # sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
    # systemctl restart sshd.service
    # SHELL
    
    config.vm.network "forwarded_port", guest: 22, host: 2522
    config.vm.network "private_network", ip: "192.168.56.11"
    config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
    end
end